services:
  - docker

script:
  - docker build -t bmxmale/docker-mysql-data-initializer:5.7 .

  - docker run -it -v `pwd`/mysql:/var/lib/mysql bmxmale/docker-mysql-data-initializer:5.7
  - ls -lash mysql | grep docker
  - sudo rm -rf mysql